from tkinter import *
top=Tk()
top.geometry("1400x800")
top.title('CLASS')
top.config(bg="brown")
welcome=Label(top,text="Welcome to our page",font=('TimesNewRoman',30,'italic'),fg='white',bg='brown')
welcome.place(x=500,y=75)
def login():
    Kit=Frame(top,bg="navyblue",height=700,width=400)
    Kit.pack(fill=X)
    label1=Label(Kit,text="Login page",font=('TimesNewRoman',50,'italic'),bg="navyblue",fg="white")
    label1.place(x=500,y=100)
    label1=Label(Kit,text="username:",font=('TimesNewRoman',35,'italic'),bg="navyblue",fg="white")
    label1.place(x=500,y=300)
    label1=Label(Kit,text="password:",font=('TimesNewRoman',35,'italic'),bg="navyblue",fg="white")
    label1.place(x=500,y=415)
    box=Entry(Kit,text="",font=('TimesNewRoman',15,'italic'),bg="white",fg="blue")
    box.place(x=800,y=315,width=300,height=50)
    box=Entry(Kit,text="*",font=('TimesNewRoman',15,'italic'),bg="white",fg="blue")
    box.place(x=800,y=425,width=300,height=50)
    label1=Label(Kit,text="dont have an account?",font=('TimesNewRoman',30,'italic'),bg="navyblue",fg="white")
    label1.place(x=400,y=600)
    label1=Label(Kit,text="Login ",font=('TimesNewRoman',30,'italic'),bg="white",fg="navyblue")
    label1.place(x=650,y=500)
    label1=Label(Kit,text="sign in",font=('TimesNewRoman',30,'italic'),bg="white",fg="navyblue")
    label1.place(x=900,y=600)
    file=File(kit,text="username",font=('TimesNewRoman',15,'italic'),bg="white",fg="brown",activebackground="black",activeforeground="orange",command=login)
    file.place(x=800,y=400,height=100,width=300)
button=Button(top,text='Get Started',font=('TimesNewRoman',30,'italic'),bg="white",fg="brown",activebackground="black",activeforeground="orange",command=login)
button.place(x=800,y=400,height=100,width=300)
top.mainloop()

